# Cloud Build configuration for HSS Backend (FULLY FIXED)
# Triggers: develop branch (dev), v* tags (prod)
# 
# FIX: Tüm bash değişkenleri MY_ prefix'i ile başlıyor (Cloud Build built-in'lerle çakışmayı önler ve güvenli bir şekilde çalışır docker build ve push işlemlerinde)

steps:
  # 1. Debug - Değişkenleri kontrol et
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-variables'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Build değişkenleri kontrol ediliyor..."
        echo "PROJECT_ID: ${PROJECT_ID}"
        echo "REGION: ${_REGION}"
        echo "REPO_NAME: ${_REPO_NAME}"
        echo "TAG_NAME: ${_TAG_NAME}"
        echo "SERVICE_NAME: ${_SERVICE_NAME}"
        echo "ENVIRONMENT: ${_ENVIRONMENT}"
        echo "SPRING_PROFILE: ${_SPRING_PROFILE}"
        echo "CONNECTION_NAME: ${_CONNECTION_NAME}"
        echo "Full image path: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${_TAG_NAME}"
        
        # Artifact Registry repository'nin var olup olmadığını kontrol et
        echo "📦 Artifact Registry kontrol ediliyor..."
        gcloud artifacts repositories describe ${_REPO_NAME} \
          --location=${_REGION} \
          --format="value(name)" || echo "⚠️  Repository bulunamadı!"
        
        # Docker auth yapılandırması
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet
        echo "✅ Docker auth yapılandırıldı"

  # 2. Test ve Build (Maven ile)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'test-and-build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Test ve build çalıştırılıyor..."
        mvn -B clean package -DskipTests=false --fail-at-end
        echo "✅ Build başarılı!"
    waitFor: ['debug-variables']

  # 3. Docker image build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        # MY_ prefix kullanarak Cloud Build built-in'lerle çakışmayı önle
        MY_IMG_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend"
        MY_VER="${_TAG_NAME}"
        
        echo "🐳 Docker image build başlıyor..."
        echo "Image: $${MY_IMG_PATH}:$${MY_VER}"
        
        # Build
        docker build \
          --tag "$${MY_IMG_PATH}:$${MY_VER}" \
          --tag "$${MY_IMG_PATH}:latest" \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          --build-arg VCS_REF=${COMMIT_SHA} \
          .
        
        echo "✅ Docker build başarılı!"
        docker images "$${MY_IMG_PATH}"
    waitFor: ['test-and-build']

  # 4. Docker image push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        MY_IMG_PATH="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend"
        MY_VER="${_TAG_NAME}"
        
        echo "📤 Docker image push başlıyor..."
        echo "Target: $${MY_IMG_PATH}:$${MY_VER}"
        
        # Tag'li versiyonu push et
        echo "Pushing tagged version..."
        docker push "$${MY_IMG_PATH}:$${MY_VER}"
        
        # Latest'i push et
        echo "Pushing latest..."
        docker push "$${MY_IMG_PATH}:latest"
        
        echo "✅ Docker push başarılı!"
        
        # Digest'i al ve kaydet
        MY_DIG=$$(docker inspect --format='{{index .RepoDigests 0}}' "$${MY_IMG_PATH}:$${MY_VER}" | cut -d'@' -f2)
        echo "Image Digest: $$MY_DIG"
        echo "$$MY_DIG" > /workspace/image-digest.txt
    waitFor: ['docker-build']

  # 5. Cloud Run deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'cloud-run-deploy'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        set -euo pipefail
        
        MY_IMG_FULL="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${_TAG_NAME}"
        
        echo "🚀 Cloud Run deploy başlıyor..."
        echo "Image: $$MY_IMG_FULL"
        echo "Service: ${_SERVICE_NAME}"
        echo "Region: ${_REGION}"
        echo "Environment: ${_ENVIRONMENT}"
        echo "Spring Profile: ${_SPRING_PROFILE}"
        echo "Connection Name: ${_CONNECTION_NAME}"
        
        # Mevcut revision'ı kaydet (rollback için)
        MY_CURR_REV=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.latestReadyRevisionName)' 2>/dev/null || echo "none")
        
        echo "📝 Mevcut revision: $$MY_CURR_REV"
        
        # Deploy
        gcloud run deploy ${_SERVICE_NAME} \
          --image="$$MY_IMG_FULL" \
          --region=${_REGION} \
          --service-account=${_SERVICE_ACCOUNT} \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="SPRING_PROFILES_ACTIVE=${_SPRING_PROFILE},DEPLOYMENT_VERSION=${_VERSION},BUILD_ID=${BUILD_ID}" \
          --set-env-vars="GCP_SQL_INSTANCE_CONNECTION_NAME=${_CONNECTION_NAME}" \
          --set-env-vars="DB_NAME=hss_dev" \
          --set-env-vars="JAVA_OPTS=-Xmx512m -XX:+UseG1GC -Dspring.profiles.active=${_SPRING_PROFILE}" \
          --set-secrets="DB_USERNAME=${_DB_USERNAME_SECRET}:latest,DB_PASSWORD=${_DB_PASSWORD_SECRET}:latest" \
          --add-cloudsql-instances=${_CONNECTION_NAME} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --port=8080 \
          --memory=1Gi \
          --cpu=2 \
          --timeout=600 \
          --concurrency=80 \
          --no-cpu-throttling \
          --cpu-boost \
          --execution-environment=gen2 \
          --quiet
        
        # Service URL'i al
        MY_SVC_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')
        
        echo "✅ Deploy başarılı!"
        echo "🌐 Service URL: $$MY_SVC_URL"
        
        # Detaylı health check
        echo "🔍 Health check yapılıyor..."
        echo "Service URL: $$MY_SVC_URL"
        echo "Health check endpoint: $$MY_SVC_URL/actuator/health"
        
        # Service'in tamamen hazır olması için daha uzun bekle
        echo "⏳ Service'in başlamasını bekliyoruz (120 saniye)..."
        sleep 120
        
        # Health check'i birkaç kez dene
        for i in {1..5}; do
          echo "🔄 Health check denemesi $i/5..."
          if curl -sf -m 60 "$$MY_SVC_URL/actuator/health" > /dev/null 2>&1; then
            echo "✅ Health check başarılı!"
            break
          else
            echo "❌ Health check başarısız (deneme $i/5)"
            if [ $i -lt 5 ]; then
              echo "⏳ 30 saniye bekleyip tekrar denenecek..."
              sleep 30
            fi
          fi
        done
        
        # Son kontrol
        if curl -sf -m 60 "$$MY_SVC_URL/actuator/health" > /dev/null 2>&1; then
          echo "✅ Final health check başarılı!"
        else
          echo "⚠️  Health check başarısız oldu, ancak deploy tamamlandı"
          echo "Manuel kontrol edin: $$MY_SVC_URL/actuator/health"
          echo "Cloud Run logs: https://console.cloud.google.com/run/detail/${_REGION}/${_SERVICE_NAME}/logs"
          
          # Container logs'unu al
          echo "📋 Container logs'unu alıyoruz..."
          gcloud run services logs read ${_SERVICE_NAME} --region=${_REGION} --limit=50 --format="value(textPayload)" || echo "Logs alınamadı"
        fi
    waitFor: ['docker-push']

  # 6. Release artifacts (sadece prod için)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'create-artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        if [ "${_ENVIRONMENT}" = "prod" ]; then
          echo "📦 Release artifacts oluşturuluyor..."
          
          MY_IMG_FULL="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hss-backend:${_TAG_NAME}"
          
          # Image digest'i al
          if [ -f /workspace/image-digest.txt ]; then
            MY_DIG=$$(cat /workspace/image-digest.txt)
          else
            MY_DIG="unknown"
          fi
          
          # Backend image referansı
          echo "$$MY_IMG_FULL" > backend-image.txt
          
          # Manifest oluştur
          cat > manifest.json << EOF
        {
          "version": "${_VERSION}",
          "environment": "${_ENVIRONMENT}",
          "commit_sha": "${COMMIT_SHA}",
          "build_id": "${BUILD_ID}",
          "changes": ["Backend ${_ENVIRONMENT} deployment"],
          "artifacts": {
            "backend": {
              "image": "$$MY_IMG_FULL",
              "tag": "${_TAG_NAME}",
              "digest": "$$MY_DIG"
            }
          },
          "deployed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "deployed_by": "cloud-build"
        }
        EOF
          
          # Cloud Storage'a yükle
          gsutil -m cp backend-image.txt "gs://${_BUCKET_NAME}/releases/${_VERSION}/"
          gsutil -m cp manifest.json "gs://${_BUCKET_NAME}/releases/${_VERSION}/"
          
          # Latest pointer'ını güncelle
          gsutil -m cp manifest.json "gs://${_BUCKET_NAME}/releases/latest/manifest.json"
          
          echo "✅ Release artifacts oluşturuldu: gs://${_BUCKET_NAME}/releases/${_VERSION}/"
        else
          echo "ℹ️  ${_ENVIRONMENT} environment - release artifacts atlandı"
        fi
    waitFor: ['cloud-run-deploy']

  # 7. Monitoring
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'monitoring'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        
        echo "📊 Deployment log kaydediliyor..."
        
        # Structured log
        cat << EOF | gcloud logging write hss-deployment \
          --severity=INFO \
          --resource=global \
          --payload-type=json
        {
          "service": "hss-backend",
          "environment": "${_ENVIRONMENT}",
          "version": "${_VERSION}",
          "commit_sha": "${COMMIT_SHA}",
          "build_id": "${BUILD_ID}",
          "tag_name": "${_TAG_NAME}",
          "deployment_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "status": "success",
          "region": "${_REGION}",
          "service_name": "${_SERVICE_NAME}"
        }
        EOF
        
        echo "✅ Deployment başarıyla tamamlandı!"
    waitFor: ['create-artifacts']

# Substitution variables
substitutions:
  _REGION: 'europe-west3'
  _REPO_NAME: 'hss-backend'
  _SERVICE_ACCOUNT: 'hss-backend-sa@hss-cloud-473511.iam.gserviceaccount.com'
  _CONNECTION_NAME: 'hss-cloud-473511:europe-west3:hss-sql'
  _DB_USERNAME_SECRET: 'DB_USERNAME'
  _DB_PASSWORD_SECRET: 'DB_PASSWORD'
  _ENVIRONMENT: 'dev'
  _SERVICE_NAME: 'hss-backend-dev'
  _SPRING_PROFILE: 'dev'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '2'
  _VERSION: 'dev'
  _BUCKET_NAME: 'hss-releases-hss-cloud-473511'
  _TAG_NAME: 'dev-manual'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true

# Timeout
timeout: '1200s'