steps:
  # 1) Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # 2) Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}'

  # 3) Deploy to Cloud Run (Blue-Green Stratejisi)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${BUILD_ID}'
      - '--region=${_REGION}'
      - '--no-traffic'
      - '--tag=green'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=${_TIMEOUT}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--port=${_PORT}'
      - '--project=${_PROJECT_ID}'
      - '--add-cloudsql-instances=${_SQL_INSTANCE_CONNECTION_NAME}'
      - '--update-env-vars=SPRING_PROFILES_ACTIVE=${_SPRING_PROFILE},GCP_SQL_INSTANCE_CONNECTION_NAME=${_SQL_INSTANCE_CONNECTION_NAME},GCP_PROJECT_ID=${_PROJECT_ID},GCP_STORAGE_BUCKET=${_STORAGE_BUCKET},JWT_ISSUER_URI=${_JWT_ISSUER_URI},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - '--set-secrets=SPRING_DATASOURCE_USERNAME=SPRING_DATASOURCE_USERNAME_PROD:latest,SPRING_DATASOURCE_PASSWORD=SPRING_DATASOURCE_PASSWORD_PROD:latest'

substitutions:
  _PROJECT_ID: 'hss-cloud-473511'
  _REGION: 'europe-west3'
  _SERVICE_NAME: 'hss-backend'
  _ENVIRONMENT: 'production'
  _SPRING_PROFILE: 'prod'
  _SQL_INSTANCE_CONNECTION_NAME: 'hss-cloud-473511:europe-west3:hss-sql'
  _STORAGE_BUCKET: 'hss-files'
  _JWT_ISSUER_URI: 'https://securetoken.google.com/hss-cloud-473511'
  _FIREBASE_PROJECT_ID: 'hss-cloud-473511'
  _MEMORY: '2Gi'
  _CPU: '2'
  _TIMEOUT: '3600'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '1'
  _PORT: '8080'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  substitution_option: 'ALLOW_LOOSE'

timeout: '1800s'
