# Simple Cloud Build configuration for HSS Backend
steps:
  # 1. Test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Backend testleri çalıştırılıyor..."
        ./mvnw -B test
        echo "✅ Testler başarılı!"

  # 2. Build
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔨 Backend build ediliyor..."
        ./mvnw -B clean package -DskipTests
        echo "✅ Build başarılı!"

  # 3. Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/hss-backend/hss-backend:$SHORT_SHA'
      - '.'

  # 4. Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/hss-backend/hss-backend:$SHORT_SHA'

  # 5. Cloud Run deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Cloud Run'a deploy ediliyor..."
        gcloud run deploy hss-backend-dev \
          --image=europe-west3-docker.pkg.dev/$PROJECT_ID/hss-backend/hss-backend:$SHORT_SHA \
          --region=europe-west3 \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=2 \
          --port=8080
        echo "✅ Cloud Run deploy başarılı!"

# Images to be pushed
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/hss-backend/hss-backend:$SHORT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'
