package com.hss.hss_backend.mapper;

import com.hss.hss_backend.dto.request.ClinicCreateRequest;
import com.hss.hss_backend.dto.response.ClinicResponse;
import com.hss.hss_backend.entity.Clinic;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@Component
public class ClinicMapper {

  public Clinic toEntity(ClinicCreateRequest request) {
    return Clinic.builder()
        .name(request.getName())
        .address(request.getAddress())
        .phone(request.getPhone())
        .email(request.getEmail())
        // licenseKey is generated by service
        .build();
  }

  public ClinicResponse toResponse(Clinic clinic) {
    return ClinicResponse.builder()
        .clinicId(clinic.getClinicId())
        .name(clinic.getName())
        .address(clinic.getAddress())
        .phone(clinic.getPhone())
        .email(clinic.getEmail())
        .licenseKey(clinic.getLicenseKey())
        .licenseType(clinic.getLicenseType())
        .licenseStartDate(clinic.getLicenseStartDate())
        .licenseEndDate(clinic.getLicenseEndDate())
        .licenseStatus(clinic.getLicenseStatus())
        .settings(clinic.getSettings())
        .build();
  }

  public List<ClinicResponse> toResponseList(List<Clinic> clinics) {
    return clinics.stream()
        .map(this::toResponse)
        .collect(Collectors.toList());
  }
}
