name: Backend CI/CD

on:
  push:
    branches:
      - main  # Production
      - dev   # Development
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: hss-cloud-473511
  REGION: europe-west3
  REPOSITORY: hss-repo
  SERVICE_NAME: hss-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Skip tests for now
      run: echo "Tests skipped - focusing on deployment"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/296268886725/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
        service_account: github-actions-backend@hss-cloud-473511.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Determine environment
      id: env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "ENV=prod" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=hss-backend-prod" >> $GITHUB_OUTPUT
        else
          echo "ENV=dev" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=hss-backend-dev" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }}
        IMAGE_LATEST=europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest
        docker build -t $IMAGE_TAG -t $IMAGE_LATEST .
        docker push $IMAGE_TAG
        docker push $IMAGE_LATEST

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ steps.env.outputs.SERVICE_NAME }} \
          --image=europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated \
          --set-env-vars="SPRING_PROFILES_ACTIVE=${{ steps.env.outputs.ENV }}" \
          --set-secrets="DB_USERNAME=db-username:latest,DB_PASSWORD=db-password:latest,GCP_SQL_INSTANCE_CONNECTION_NAME=sql-connection-name:latest,JWT_ISSUER_URI=jwt-issuer-uri:latest" \
          --add-cloudsql-instances=$PROJECT_ID:$REGION:hss-sql \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --min-instances=0 \
          --max-instances=10
